-- MySQL Script generated by MySQL Workbench
-- Fri Jan 10 17:15:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema user
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `user` ;

-- -----------------------------------------------------
-- Schema user
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
SHOW WARNINGS;
USE `user` ;

-- -----------------------------------------------------
-- Table `user`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`user` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(100) NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email_address` VARCHAR(100) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `otp` MEDIUMINT NULL,
  `mac_address` VARCHAR(1000) NULL,
  `allowed_ip` VARCHAR(45) NULL,
  `last_login` TIMESTAMP NULL,
  `last_login_ip_address` VARCHAR(45) NULL,
  `is_admin` TINYINT NOT NULL DEFAULT 0,
  `image_url` TEXT NULL,
  `reporting_to_id` BIGINT NULL,
  `country` VARCHAR(100) NULL,
  `state` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `token` VARCHAR(1000) NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;
CREATE UNIQUE INDEX `u_email_addr` ON `user`.`user` (`email_address` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`role` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`role` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(50) NOT NULL,
  `role_desc` VARCHAR(500) NOT NULL,
  `role_bit` BIGINT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `u_name` ON `user`.`role` (`role_name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`privilege`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`privilege` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`privilege` (
  `privilege_id` INT(11) NOT NULL AUTO_INCREMENT,
  `privilege_name` VARCHAR(50) NOT NULL,
  `privilege_desc` VARCHAR(500) NOT NULL,
  `privilege_bit` MEDIUMINT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`privilege_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `u_priv_name` ON `user`.`privilege` (`privilege_name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`module` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`module` (
  `module_id` INT(11) NOT NULL,
  `module_name` VARCHAR(50) NOT NULL,
  `module_desc` VARCHAR(500) NOT NULL,
  `module_bit` BIGINT(20) NOT NULL,
  `route_name` VARCHAR(200) NOT NULL,
  `module_icon` VARCHAR(200) NOT NULL,
  `module_alias` VARCHAR(200) NOT NULL,
  `module_type` VARCHAR(45) NOT NULL,
  `module_group` VARCHAR(200) NOT NULL,
  `module_group_sort_order` MEDIUMINT NOT NULL,
  `module_sort_order` MEDIUMINT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`module_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `u_module_name` ON `user`.`module` (`module_name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`user_role_company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`user_role_company` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`user_role_company` (
  `user_role_company_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `role_id` INT(11) NOT NULL,
  `company_id` BIGINT NOT NULL,
  `module_id` INT NOT NULL,
  `privilege_list` VARCHAR(1000) NOT NULL,
  `privilege_mask` MEDIUMINT NOT NULL DEFAULT 0,
  `group_list` VARCHAR(1000) NULL,
  `group_mask` MEDIUMINT NULL,
  `status` TINYINT NOT NULL,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_role_company_id`),
  CONSTRAINT `fk_urc_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `user`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_urc_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `user`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_urc_module`
    FOREIGN KEY (`module_id`)
    REFERENCES `user`.`module` (`module_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_urc_role` ON `user`.`user_role_company` (`role_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_urc_user_idx` ON `user`.`user_role_company` (`user_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `u_user_company_module` ON `user`.`user_role_company` (`user_id` ASC, `company_id` ASC, `module_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_urc_module_idx` ON `user`.`user_role_company` (`module_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`notification_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`notification_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`notification_type` (
  `notification_type_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` BIGINT NOT NULL,
  `module_id` INT(11) NOT NULL,
  `role_mask` BIGINT NOT NULL,
  `notification_type_name` VARCHAR(45) NOT NULL,
  `notification_type_description` VARCHAR(100) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`notification_type_id`),
  CONSTRAINT `fk_notf_type_module`
    FOREIGN KEY (`module_id`)
    REFERENCES `user`.`module` (`module_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_notf_type_module_idx` ON `user`.`notification_type` (`module_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `u_comp_mod_notf_name` ON `user`.`notification_type` (`company_id` ASC, `module_id` ASC, `notification_type_name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`user_notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`user_notification` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`user_notification` (
  `user_notification_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `notification_type_id` INT NOT NULL,
  `notification_name` VARCHAR(100) NOT NULL,
  `notification_message` TEXT NOT NULL,
  `notification_effective_from` DATETIME NULL,
  `notification_effective_to` DATETIME NULL,
  `notification_lifespan_days` TINYINT NULL,
  `notification_publish_flag` TINYINT NOT NULL,
  `acknowledgment_required` TINYINT NOT NULL,
  `notification_acknowledged_on` TIMESTAMP NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_notification_id`),
  CONSTRAINT `fk_notification_notification_type`
    FOREIGN KEY (`notification_type_id`)
    REFERENCES `user`.`notification_type` (`notification_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_notif_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `user`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_notification_notification_type` ON `user`.`user_notification` (`notification_type_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_user_notif_user_idx` ON `user`.`user_notification` (`user_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`user_template_docs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`user_template_docs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`user_template_docs` (
  `user_template_docs_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_template_type_name` VARCHAR(300) NOT NULL,
  `user_template_doc` BLOB NULL,
  `linked_user_template_docs_id` BIGINT NULL,
  `action_type` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_template_docs_id`),
  CONSTRAINT `fk_self_user_template_docs_id`
    FOREIGN KEY (`linked_user_template_docs_id`)
    REFERENCES `user`.`user_template_docs` (`user_template_docs_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `u_user_template_type_name` ON `user`.`user_template_docs` (`user_template_type_name` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_self_user_template_docs_id_idx` ON `user`.`user_template_docs` (`linked_user_template_docs_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`user_template_action_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`user_template_action_log` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`user_template_action_log` (
  `user_template_action_log_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Outbound - any attachments to the user\nInbound - uploads from user',
  `user_template_docs_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `user_template_data_doc` BLOB NOT NULL,
  `action_dtm` TIMESTAMP NOT NULL,
  `action_by_id` BIGINT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_template_action_log_id`),
  CONSTRAINT `fk_utal_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `user`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utal_utd`
    FOREIGN KEY (`user_template_docs_id`)
    REFERENCES `user`.`user_template_docs` (`user_template_docs_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_utal_user_idx` ON `user`.`user_template_action_log` (`user_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_utal_utd_idx` ON `user`.`user_template_action_log` (`user_template_docs_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`user_audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`user_audit` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`user_audit` (
  `user_audit_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NULL,
  `designation` VARCHAR(100) NULL DEFAULT NULL,
  `first_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NULL,
  `email_address` VARCHAR(100) NULL,
  `password` VARCHAR(128) NULL,
  `phone` VARCHAR(20) NULL,
  `otp` MEDIUMINT NULL,
  `mac_address` VARCHAR(1000) NULL,
  `allowed_ip` VARCHAR(45) NULL,
  `last_login` TIMESTAMP NULL,
  `last_login_ip_address` VARCHAR(45) NULL,
  `is_admin` TINYINT NULL,
  `image_url` TEXT NULL DEFAULT NULL,
  `reporting_to_id` BIGINT NULL,
  `country` VARCHAR(100) NULL,
  `state` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  `token` VARCHAR(1000) NULL,
  `created_id` BIGINT NULL,
  `created_dtm` TIMESTAMP NULL,
  `modified_id` BIGINT NULL,
  `modified_dtm` TIMESTAMP NULL,
  `audit_action` VARCHAR(5) NULL DEFAULT NULL,
  `audit_dtm` TIMESTAMP NULL,
  PRIMARY KEY (`user_audit_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`user_role_company_audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`user_role_company_audit` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`user_role_company_audit` (
  `user_role_company_audit_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_role_company_id` BIGINT NULL,
  `user_id` BIGINT NULL,
  `role_id` INT(11) NULL,
  `company_id` BIGINT NULL,
  `module_id` INT NULL,
  `privilege_list` VARCHAR(1000) NULL,
  `privilege_mask` MEDIUMINT NULL,
  `group_list` VARCHAR(1000) NULL,
  `group_mask` MEDIUMINT NULL,
  `status` TINYINT NULL,
  `created_id` BIGINT NULL,
  `created_dtm` TIMESTAMP NULL,
  `modified_id` BIGINT NULL,
  `modified_dtm` TIMESTAMP NULL,
  `audit_action` VARCHAR(5) NULL DEFAULT NULL,
  `audit_dtm` TIMESTAMP NULL,
  PRIMARY KEY (`user_role_company_audit_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`user_notification_audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`user_notification_audit` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`user_notification_audit` (
  `user_notification_audit_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_notification_id` BIGINT NULL,
  `user_id` BIGINT NULL,
  `notification_type_id` INT NULL,
  `notification_name` VARCHAR(100) NULL,
  `notification_message` TEXT NULL,
  `notification_effective_from` DATETIME NULL DEFAULT NULL,
  `notification_effective_to` DATETIME NULL DEFAULT NULL,
  `notification_lifespan_days` TINYINT NULL DEFAULT NULL,
  `notification_publish_flag` TINYINT NULL,
  `acknowledgment_required` TINYINT NULL,
  `notification_acknowledged_on` TIMESTAMP NULL,
  `status` TINYINT NULL,
  `created_id` BIGINT NULL,
  `created_dtm` TIMESTAMP NULL,
  `modified_id` BIGINT NULL,
  `modified_dtm` TIMESTAMP NULL,
  `audit_action` VARCHAR(5) NULL DEFAULT NULL,
  `audit_dtm` TIMESTAMP NULL,
  PRIMARY KEY (`user_notification_audit_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`user_template_action_log_audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`user_template_action_log_audit` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`user_template_action_log_audit` (
  `user_template_action_log_audit_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_template_action_log_id` BIGINT NULL,
  `user_template_docs_id` BIGINT NULL,
  `user_id` BIGINT NULL,
  `user_template_data_doc` BLOB NULL,
  `action_dtm` TIMESTAMP NULL,
  `action_by_id` BIGINT NULL,
  `status` TINYINT NULL,
  `created_id` BIGINT NULL,
  `created_dtm` TIMESTAMP NULL,
  `modified_id` BIGINT NULL,
  `modified_dtm` TIMESTAMP NULL,
  `audit_action` VARCHAR(5) NULL DEFAULT NULL,
  `audit_dtm` TIMESTAMP NULL,
  PRIMARY KEY (`user_template_action_log_audit_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`user_activity_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`user_activity_log` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`user_activity_log` (
  `user_activity_log_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `activity_type` VARCHAR(45) NOT NULL,
  `activity_doc_pk_id` BIGINT NOT NULL,
  `activity_doc_num` VARCHAR(100) NULL DEFAULT NULL,
  `activity_detail` TEXT NULL DEFAULT NULL,
  `activity_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_activity_log_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `i_activity_dtm` ON `user`.`user_activity_log` (`activity_dtm` ASC);

SHOW WARNINGS;
CREATE INDEX `i_user_activity_dtm` ON `user`.`user_activity_log` (`user_id` ASC, `activity_dtm` ASC);

SHOW WARNINGS;
CREATE INDEX `i_activity_type` ON `user`.`user_activity_log` (`activity_type` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`user_preference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`user_preference` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`user_preference` (
  `user_preference_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `preferred_module_ids` TEXT NULL,
  `preferred_notification_type_ids` TEXT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_preference_id`),
  CONSTRAINT `fk_user_user_preference`
    FOREIGN KEY (`user_id`)
    REFERENCES `user`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_user_user_preference_idx` ON `user`.`user_preference` (`user_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`user_preference_audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`user_preference_audit` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`user_preference_audit` (
  `user_preference_audit_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_preference_id` BIGINT NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  `preferred_module_ids` TEXT NULL DEFAULT NULL,
  `preferred_notification_type_ids` TEXT NULL DEFAULT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `created_id` BIGINT NULL DEFAULT NULL,
  `created_dtm` TIMESTAMP NULL DEFAULT NULL,
  `modified_id` BIGINT NULL DEFAULT NULL,
  `modified_dtm` TIMESTAMP NULL DEFAULT NULL,
  `audit_action` VARCHAR(5) NULL DEFAULT NULL,
  `audit_dtm` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`user_preference_audit_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`user_company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`user_company` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`user_company` (
  `user_company_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `company_id` BIGINT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_company_id`),
  CONSTRAINT `fk_uc_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `user`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_uc_user_idx` ON `user`.`user_company` (`user_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`ticket_status_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`ticket_status_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`ticket_status_type` (
  `ticket_status_type_id` BIGINT NOT NULL AUTO_INCREMENT,
  `ticket_status_type_name` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ticket_status_type_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`ticket_issue_category_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`ticket_issue_category_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`ticket_issue_category_type` (
  `ticket_issue_category_type_id` BIGINT NOT NULL AUTO_INCREMENT,
  `ticket_issue_category_type_name` VARCHAR(100) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ticket_issue_category_type_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`ticket` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`ticket` (
  `ticket_id` BIGINT NOT NULL AUTO_INCREMENT,
  `ticket_status_type_id` BIGINT NOT NULL,
  `ticket_issue_category_type_id` BIGINT NOT NULL,
  `ticket_raised_by_id` BIGINT NOT NULL,
  `ticket_raised_dtm` TIMESTAMP NOT NULL,
  `ticket_resolved_dtm` TIMESTAMP NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ticket_id`),
  CONSTRAINT `fk_tkt_status_type_id`
    FOREIGN KEY (`ticket_status_type_id`)
    REFERENCES `user`.`ticket_status_type` (`ticket_status_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tkt_issue_cat_id`
    FOREIGN KEY (`ticket_issue_category_type_id`)
    REFERENCES `user`.`ticket_issue_category_type` (`ticket_issue_category_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tkt_raised_by_id`
    FOREIGN KEY (`ticket_raised_by_id`)
    REFERENCES `user`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_ticket_status_type_id_idx` ON `user`.`ticket` (`ticket_status_type_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_tkt_issue_cat_id_idx` ON `user`.`ticket` (`ticket_issue_category_type_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_tkt_raised_by_id_idx` ON `user`.`ticket` (`ticket_raised_by_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user`.`comment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user`.`comment` (
  `comment_id` BIGINT NOT NULL AUTO_INCREMENT,
  `ticket_id` BIGINT NOT NULL,
  `comment` VARCHAR(1000) NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`comment_id`),
  CONSTRAINT `fk_ticket_id`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `user`.`ticket` (`ticket_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_ticket_id_idx` ON `user`.`comment` (`ticket_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `user`.`role`
-- -----------------------------------------------------
START TRANSACTION;
USE `user`;
INSERT INTO `user`.`role` (`role_id`, `role_name`, `role_desc`, `role_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (1, 'READ_ONLY', 'READ ONLY DEFAULT ROLE', 1, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`role` (`role_id`, `role_name`, `role_desc`, `role_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (2, 'SUPERUSER', 'SUPERUSER ROLE', 2, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`role` (`role_id`, `role_name`, `role_desc`, `role_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (3, 'ADMIN', 'ADMINISTRATOR ROLE', 4, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`role` (`role_id`, `role_name`, `role_desc`, `role_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (4, 'GROUP HEAD', 'HEAD OF GROUP OF COMPANIES', 8, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`role` (`role_id`, `role_name`, `role_desc`, `role_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (5, 'COMPANY HEAD', 'HEAD OF A COMPANY', 16, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`role` (`role_id`, `role_name`, `role_desc`, `role_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (6, 'BUSINESS UNIT HEAD', 'HEAD OF BUSINESS UNIT', 32, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`role` (`role_id`, `role_name`, `role_desc`, `role_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (7, 'DIVISION HEAD', 'HEAD OF A DIVISION WITHIN A COMPANY', 64, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`role` (`role_id`, `role_name`, `role_desc`, `role_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (8, 'DEPARTMENT HEAD', 'HEAD A DEPARTMENT WITHIN A DIVISION OF A COMPANY', 128, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`role` (`role_id`, `role_name`, `role_desc`, `role_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (9, 'TEAM MANAGER', 'TEAM MANAGER ROLE', 256, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`role` (`role_id`, `role_name`, `role_desc`, `role_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (10, 'TEAM LEAD', 'TEAM LEAD ROLE', 512, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`role` (`role_id`, `role_name`, `role_desc`, `role_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (11, 'AGENT', 'AGENT', 1024, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`role` (`role_id`, `role_name`, `role_desc`, `role_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (12, 'SENIOR MANAGER', 'SENIOR MANAGER', 2048, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`role` (`role_id`, `role_name`, `role_desc`, `role_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (13, 'IT MANAGER', 'IT MANAGER WITHIN IT DEPARTMENT', 4096, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`role` (`role_id`, `role_name`, `role_desc`, `role_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (14, 'FIELD AGENT', 'FIELD AGENT', 8192, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');

COMMIT;


-- -----------------------------------------------------
-- Data for table `user`.`privilege`
-- -----------------------------------------------------
START TRANSACTION;
USE `user`;
INSERT INTO `user`.`privilege` (`privilege_id`, `privilege_name`, `privilege_desc`, `privilege_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (1, 'CREATE', 'CREATE PRIVILEGE', 1, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`privilege` (`privilege_id`, `privilege_name`, `privilege_desc`, `privilege_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (2, 'EDIT', 'EDIT PRIVILEGE', 2, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`privilege` (`privilege_id`, `privilege_name`, `privilege_desc`, `privilege_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (3, 'DELETE', 'DELETE PRIVILEGE', 4, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`privilege` (`privilege_id`, `privilege_name`, `privilege_desc`, `privilege_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (4, 'READ', 'READ PRIVILEGE', 8, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`privilege` (`privilege_id`, `privilege_name`, `privilege_desc`, `privilege_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (5, 'UPLOAD', 'CREATE PRIVILEGE', 16, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`privilege` (`privilege_id`, `privilege_name`, `privilege_desc`, `privilege_bit`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (6, 'APPROVE', 'CREATE PRIVILEGE', 32, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');

COMMIT;


-- -----------------------------------------------------
-- Data for table `user`.`module`
-- -----------------------------------------------------
START TRANSACTION;
USE `user`;
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (1, 'DASHBOARD', 'Dashboard', 1, 'dashboard', 'dashboard', 'Dashboard', 'list', 'DASHBOARD', 1, 1, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (2, 'ACCOUNT_MANAGEMENT', 'Account Management', 2, 'account-management', 'business', 'Account Management', 'list', 'ACCOUNT_MANAGEMENT', 2, 2, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (3, 'DETAILS', 'Details Tab under Account', 4, 'account-management/details', 'group', 'Details', 'tabs', 'ACCOUNT_MANAGEMENT', 3, 5, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (4, 'PERSONAL_INFORMATION', 'Personal Details under Details Tab of Account', 8, 'acount-management/details/personal', 'settings_applications', 'Personal Information', 'sub_tab', 'ACCOUNT_MANAGEMENT', 3, 6, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (5, 'ADDITIONAL_INFORMATION', 'Additional Information under Details of Account', 16, 'acount-management/details/additional-info', 'pie_chart', 'Additional Information', 'sub_tab', 'ACCOUNT_MANAGEMENT', 3, 1, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (6, 'TASKS', 'Tasks View and Create', 32, 'account-management/tasks', 'today', 'Tasks', 'tabs', 'ACCOUNT_MANAGEMENT', 4, 2, 1, 1, '2024-03-16 13:00:12', 1, '2024-06-01 09:21:38');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (7, 'CASE_HISTORY', 'Case History of Account', 64, 'account-management/case-history', 'calendar_today', 'Case History', 'tabs', 'ACCOUNT_MANAGEMENT', 5, 4, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (8, 'FIELD_VISIT_STATUS', 'Field Visit Status on Account', 128, 'account-management/case-history/field-visit', 'manage_accounts', 'Field Visit', 'sub_tab', 'ACCOUNT_MANAGEMENT', 5, 1, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (9, 'POLICE_EXECUTION_CASE_DETAILS', 'Police and Execution Case Details of Account', 256, 'account-management/case-history/police-exec-details', 'add_shopping_cart', 'Police and Execution Case Details', 'sub_tab', 'ACCOUNT_MANAGEMENT', 5, 2, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (10, 'LOGS_AND_INTERACTIONS', 'Logs and Interactions on Account', 512, 'account-management/case-history/logs-interactions', 'live_help', 'Logs and Interactions', 'sub_tab', 'ACCOUNT_MANAGEMENT', 5, 3, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (11, 'FOLLOW_UP', 'Follow Up Logs on Accounts', 1024, 'account-management/follow-up', 'receipt', 'Follow up', 'tabs', 'ACCOUNT_MANAGEMENT', 6, 4, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (12, 'DOCUMENTS', 'Documents', 2048, 'account-management/documents', 'credit_score', 'Documents', 'tabs', 'ACCOUNT_MANAGEMENT', 7, 5, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (13, 'TASK_DOCUMENTS', 'Task Documents upload', 4096, 'account-management/documents/tasks', 'filter_2', 'Task Documents', 'sub_tab', 'ACCOUNT_MANAGEMENT', 7, 2, 0, 1, '2024-03-16 13:00:12', 1, '2024-06-01 12:59:33');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (14, 'SQ_CHECK', 'SQ Check', 8192, 'account-managementsq-check', 'filter_3', 'SQ Check', 'tabs', 'ACCOUNT_MANAGEMENT', 8, 3, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (15, 'BANK_MANAGEMENT', 'Bank Management', 16384, 'bank-management', 'support_agent', 'Bank Management', 'list', 'BANK_MANAGEMENT', 9, 1, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (16, 'USER_MANAGEMENT', 'User Management', 32768, 'user-management', 'person', 'User Management', 'list', 'USER_MANAGEMENT', 10, 0, 1, 1, '2024-03-16 13:00:12', 1, '2024-03-16 13:00:12');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (17, 'ACTIVITY_LOGS', 'Activity Logs', 65536, 'activity-logs', 'sync_alt', 'Activity Logs', 'list', 'ACTIVITY_LOGS', 11, 0, 1, 1, '2024-04-23 15:44:10', 1, '2024-04-23 15:44:10');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (18, 'DISPOSITION_CODE', 'Disposition Code', 131072, 'disposition-code', 'control_camera', 'Disposition Code', 'list', 'DISPOSITION_CODE', 14, 0, 1, 1, '2024-04-23 15:44:10', 1, '2024-04-23 15:44:10');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (19, 'PRELIMINARY_CHECKS', 'Preliminary Checks', 262144, 'prliminary-checks', 'control_camera', 'Preliminary Checks', 'sub_tab', 'ACCOUNT_MANAGEMENT', 14, 0, 1, 1, '2024-04-23 15:44:10', 1, '2024-04-23 15:44:10');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (20, 'CALL_REMINDER', 'Call Reminder', 524288, 'call-reminder', 'control_camera', 'Call Reminder', 'sub_tab', 'ACCOUNT_MANAGEMENT', 14, 0, 1, 1, '2024-04-23 15:44:10', 1, '2024-04-23 15:44:10');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (21, 'CONTACTS', 'Contact', 1048576, 'contact', 'call', 'Contacts', 'sub_tab', 'ACCOUNT_MANAGEMENT', 14, 0, 1, 1, '2024-04-23 15:44:10', 1, '2024-04-23 15:44:10');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (22, 'ADDRESS', 'Address', 2097152, 'address', 'home', 'Address', 'sub_tab', 'ACCOUNT_MANAGEMENT', 14, 0, 1, 1, '2024-04-23 15:44:10', 1, '2024-04-23 15:44:10');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (23, 'PAYMENT_LEDGER', 'Payment Ledger', 4194304, 'account-management/payment-ledger', 'home', 'Payment Ledger', 'sub_tab', 'ACCOUNT_MANAGEMENT', 14, 0, 1, 1, '2024-04-23 15:44:10', 1, '2024-04-23 15:44:10');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (24, 'REPORTS', 'Reports', 8388608, 'reports', 'lab_profile', 'Reports', 'list', 'REPORTS', 14, 0, 1, 1, '2024-04-23 15:44:10', 1, '2024-04-23 15:44:10');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (25, 'SUPPORT', 'Support', 16777216, 'support', 'contact_support', 'Support', 'list', 'SUPPORT', 14, 0, 1, 1, '2024-04-23 15:44:10', 1, '2024-04-23 15:44:10');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (26, 'VISA_CHECK', 'Visa Check', 33554432, 'visa-check', 'badge', 'Visa Check', 'sub_tab', 'ACCOUNT_MANAGEMENT', 14, 0, 1, 1, '2024-04-23 15:44:10', 1, '2024-04-23 15:44:10');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (27, 'MOL_CHECK', 'MOL Check', 67108864, 'mol-check', 'fact_check', 'MOL Check', 'sub_tab', 'ACCOUNT_MANAGEMENT', 14, 0, 1, 1, '2024-04-23 15:44:10', 1, '2024-04-23 15:44:10');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (28, 'TRACING_DETAILS', 'Tracing Details', 134217728, 'tracing-details', 'person_search', 'Tracing Details', 'sub_tab', 'ACCOUNT_MANAGEMENT', 14, 0, 1, 1, '2024-04-23 15:44:10', 1, '2024-04-23 15:44:10');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (29, 'WEB_TRACING_DETAILS', 'Web Tracing Details', 268435456, 'web-tracing-details', 'content_paste_search', 'Web Tracing Details', 'sub_tab', 'ACCOUNT_MANAGEMENT', 14, 0, 1, 1, '2024-04-23 15:44:10', 1, '2024-04-23 15:44:10');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (30, 'TARGETS', 'Assigning Targets', 536870912, 'targets', 'content_paste_search', 'Targets', 'list', 'TARGETS', 14, 0, 1, 1, '2024-04-23 15:44:10', 1, '2024-04-23 15:44:10');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (31, 'FIELD_VISIT_MANAGEMENT', 'Field Visit  Management ', 1073741824, 'field-management', 'content_paste_search', 'Field Visit Management', 'list', 'ACCOUNT_MANAGEMENT', 14, 0, 1, 1, '2024-04-23 15:44:10', 1, '2024-04-23 15:44:10');
INSERT INTO `user`.`module` (`module_id`, `module_name`, `module_desc`, `module_bit`, `route_name`, `module_icon`, `module_alias`, `module_type`, `module_group`, `module_group_sort_order`, `module_sort_order`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (32, 'PAYMENT_COLLECTION', 'Payment Collection', 2147483648, 'account-management/payment-collection', 'content_paste_search', 'Payment Collection', 'sub_tab', 'ACCOUNT_MANAGEMENT', 14, 0, 1, 1, '2024-04-23 15:44:10', 1, '2024-04-23 15:44:10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `user`.`notification_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `user`;
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (1, 1, 1, 0, 'USER_CREATION', 'New User Creation on User Management', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (2, 1, 1, 0, 'ACCOUNTS_UPLOAD', 'Accounts Uploaded on Account Management', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (3, 1, 1, 0, 'ACCOUNTS_ASSIGNED_BY_REASSIGN', 'Updated Accounts Assigned By', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (4, 1, 1, 0, 'ACCOUNTS_ASSIGNED_TO_REASSIGN', 'Updated Accounts Assignment To', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (5, 1, 1, 0, 'TASK_CREATION_ASSIGNED_BY', 'New Task Creation Assigned By', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (6, 1, 1, 0, 'TASK_CREATION_ASSIGNED_TO', 'New Task Creation Assigned To', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (7, 1, 1, 0, 'TASK_ASSIGNED_BY_REASSIGN', 'Updated Task Assigned By', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (8, 1, 1, 0, 'TASK_ASSIGNED_TO_REASSIGN', 'Updated Task Assigned To', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (9, 1, 1, 0, 'NOTES_ADDED', 'New Note Added on Task Details', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (10, 1, 1, 0, 'NOTES_UPDATED', 'Note Updated on Task Details', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (11, 1, 1, 0, 'CLIENT_MANAGER_ASSIGNMENT', 'New Team Manager Assigned for a Client', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (12, 1, 1, 0, 'CLIENT_LEAD_ASSIGNMENT', 'New Team Lead Assigned for a Client', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (13, 1, 1, 0, 'CALL_REMINDER', 'Call Reminder Requested', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (14, 1, 1, 0, 'ADDRESS_ADDED', 'New Address Added on Account', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (15, 1, 1, 0, 'CONTACT_ADDED', 'New Contact Added on Account', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (16, 1, 1, 0, 'VISA_CHECK_ADDED', 'New Visa Check Added on Account', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (17, 1, 1, 0, 'MOL_CHECK_ADDED', 'New MOL Check Added on Account', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (18, 1, 1, 0, 'PAYMENT_LEDGER_ENTRY_ADDED', 'New Payment Ledger Entry Added on Account', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (19, 1, 1, 0, 'TRACED_DETAILS_ADDED', 'New Traced Detail Added on Account', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (20, 1, 1, 0, 'WEB_TRACED_DETAILS_ADDED', 'New Web Traced Detail Added on Account', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (21, 1, 1, 0, 'SUPPORT', 'New Ticket Raised for Support', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');
INSERT INTO `user`.`notification_type` (`notification_type_id`, `company_id`, `module_id`, `role_mask`, `notification_type_name`, `notification_type_description`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (22, 1, 1, 0, 'IDLE_TIME', 'Users are found to be Idle', 1, 1, '2024-05-29 07:06:55', 1, '2024-05-29 07:06:55');

COMMIT;


-- -----------------------------------------------------
-- Data for table `user`.`ticket_status_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `user`;
INSERT INTO `user`.`ticket_status_type` (`ticket_status_type_id`, `ticket_status_type_name`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (1, 'PENDING', 1, 1, '2024-07-08 08:57:47', 1, '2024-07-08 08:57:47');
INSERT INTO `user`.`ticket_status_type` (`ticket_status_type_id`, `ticket_status_type_name`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (2, 'IN PROGRESS', 1, 1, '2024-07-08 08:57:47', 1, '2024-07-08 08:57:47');
INSERT INTO `user`.`ticket_status_type` (`ticket_status_type_id`, `ticket_status_type_name`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (3, 'CANCELLED', 1, 1, '2024-07-08 08:57:47', 1, '2024-07-08 08:57:47');
INSERT INTO `user`.`ticket_status_type` (`ticket_status_type_id`, `ticket_status_type_name`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (4, 'DEFERRED', 1, 1, '2024-07-08 08:57:47', 1, '2024-07-08 08:57:47');
INSERT INTO `user`.`ticket_status_type` (`ticket_status_type_id`, `ticket_status_type_name`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (5, 'COMPLETED', 1, 1, '2024-07-08 08:57:47', 1, '2024-07-08 08:57:47');

COMMIT;


-- -----------------------------------------------------
-- Data for table `user`.`ticket_issue_category_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `user`;
INSERT INTO `user`.`ticket_issue_category_type` (`ticket_issue_category_type_id`, `ticket_issue_category_type_name`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (1, 'SYSTEM HARDWARE', 1, 1, '2024-07-08 08:57:47', 1, '2024-07-08 08:57:47');
INSERT INTO `user`.`ticket_issue_category_type` (`ticket_issue_category_type_id`, `ticket_issue_category_type_name`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (2, 'SOFTWARE', 1, 1, '2024-07-08 08:57:47', 1, '2024-07-08 08:57:47');
INSERT INTO `user`.`ticket_issue_category_type` (`ticket_issue_category_type_id`, `ticket_issue_category_type_name`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (3, 'PHONE', 1, 1, '2024-07-08 08:57:47', 1, '2024-07-08 08:57:47');
INSERT INTO `user`.`ticket_issue_category_type` (`ticket_issue_category_type_id`, `ticket_issue_category_type_name`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (4, 'NETWORK ISSUE IN TRACING', 1, 1, '2024-07-08 08:57:47', 1, '2024-07-08 08:57:47');
INSERT INTO `user`.`ticket_issue_category_type` (`ticket_issue_category_type_id`, `ticket_issue_category_type_name`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (5, 'HEADSET', 1, 1, '2024-07-08 08:57:47', 1, '2024-07-08 08:57:47');
INSERT INTO `user`.`ticket_issue_category_type` (`ticket_issue_category_type_id`, `ticket_issue_category_type_name`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (6, 'MANAGEMENT APPROACH', 1, 1, '2024-07-08 08:57:47', 1, '2024-07-08 08:57:47');

COMMIT;

