-- MySQL Script generated by MySQL Workbench
-- Tue Aug  6 10:31:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema org
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `org` ;

-- -----------------------------------------------------
-- Schema org
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `org` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
SHOW WARNINGS;
USE `org` ;

-- -----------------------------------------------------
-- Table `org`.`company_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `org`.`company_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `org`.`company_type` (
  `company_type_id` INT(11) NOT NULL AUTO_INCREMENT,
  `company_type_name` VARCHAR(45) NOT NULL,
  `company_type_desc` VARCHAR(200) NOT NULL,
  `status` SMALLINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`company_type_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `u_company_name` ON `org`.`company_type` (`company_type_name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `org`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `org`.`company` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `org`.`company` (
  `company_id` BIGINT NOT NULL AUTO_INCREMENT,
  `company_type_id` INT(11) NOT NULL,
  `company_code` VARCHAR(10) NOT NULL,
  `company_name` VARCHAR(100) NOT NULL,
  `company_desc` VARCHAR(200) NOT NULL,
  `company_logo_url` VARCHAR(2000) NULL DEFAULT NULL,
  `website` VARCHAR(500) NULL,
  `country` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `account_no` VARCHAR(100) NULL,
  `iban_no` VARCHAR(100) NULL,
  `swift_code` VARCHAR(100) NULL,
  `senior_manager_id` BIGINT NULL,
  `team_manager_id` BIGINT NULL,
  `team_lead_id` BIGINT NULL,
  `status` SMALLINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`company_id`),
  CONSTRAINT `fk_company_company_type`
    FOREIGN KEY (`company_type_id`)
    REFERENCES `org`.`company_type` (`company_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `u_company_name` ON `org`.`company` (`company_name` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_company_company_type` ON `org`.`company` (`company_type_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `org`.`address_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `org`.`address_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `org`.`address_type` (
  `address_type_id` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `address_type_code` VARCHAR(45) NOT NULL,
  `address_type_name` VARCHAR(45) NOT NULL,
  `address_type_desc` VARCHAR(100) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`address_type_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `u_address_type_code` ON `org`.`address_type` (`address_type_code` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `org`.`location_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `org`.`location_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `org`.`location_type` (
  `location_type_id` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `location_type_code` VARCHAR(10) NOT NULL,
  `location_type_name` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`location_type_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `u_location_type_code` ON `org`.`location_type` (`location_type_code` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `org`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `org`.`location` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `org`.`location` (
  `location_id` BIGINT NOT NULL AUTO_INCREMENT,
  `location_name` VARCHAR(200) NOT NULL,
  `location_type_id` MEDIUMINT NOT NULL,
  `location_code` VARCHAR(10) NULL DEFAULT NULL,
  `company_id` BIGINT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`location_id`),
  CONSTRAINT `fk_location_location_type`
    FOREIGN KEY (`location_type_id`)
    REFERENCES `org`.`location_type` (`location_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_location_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `org`.`company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `u_location_name_company_id` ON `org`.`location` (`location_name` ASC, `company_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_location_location_type` ON `org`.`location` (`location_type_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_location_company` ON `org`.`location` (`company_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `org`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `org`.`address` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `org`.`address` (
  `address_id` BIGINT NOT NULL AUTO_INCREMENT,
  `location_id` BIGINT NOT NULL,
  `address_name` VARCHAR(100) NOT NULL,
  `address_type_id` MEDIUMINT NOT NULL,
  `address_line_1` VARCHAR(500) NOT NULL,
  `address_line_2` VARCHAR(500) NULL DEFAULT NULL,
  `address_line_3` VARCHAR(500) NULL DEFAULT NULL,
  `city` VARCHAR(100) NOT NULL,
  `state` VARCHAR(100) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `zipcode` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`address_id`),
  CONSTRAINT `fk_address_address_type`
    FOREIGN KEY (`address_type_id`)
    REFERENCES `org`.`address_type` (`address_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_location`
    FOREIGN KEY (`location_id`)
    REFERENCES `org`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_address_address_type` ON `org`.`address` (`address_type_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `u_location_id_address_type_id` ON `org`.`address` (`location_id` ASC, `address_type_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_address_location` ON `org`.`address` (`location_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `org`.`location_operation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `org`.`location_operation` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `org`.`location_operation` (
  `location_operation_id` BIGINT NOT NULL AUTO_INCREMENT,
  `location_id` BIGINT NOT NULL,
  `location_start_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `location_end_date` DATETIME NOT NULL DEFAULT '2100-12-31',
  `location_start_time` TIME NOT NULL DEFAULT '08:00:00',
  `location_end_time` TIME NOT NULL DEFAULT '20:00:00',
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`location_operation_id`),
  CONSTRAINT `fk_location_operation_location`
    FOREIGN KEY (`location_id`)
    REFERENCES `org`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_location_operation_location` ON `org`.`location_operation` (`location_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `u_location_id` ON `org`.`location_operation` (`location_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `org`.`contact_dept_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `org`.`contact_dept_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `org`.`contact_dept_type` (
  `contact_dept_type_id` BIGINT NOT NULL AUTO_INCREMENT,
  `contact_dept_type_name` VARCHAR(200) NOT NULL,
  `contact_dept_type_desc` VARCHAR(200) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`contact_dept_type_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `u_contact_dept_type_name` ON `org`.`contact_dept_type` (`contact_dept_type_name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `org`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `org`.`contact` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `org`.`contact` (
  `contact_id` BIGINT NOT NULL AUTO_INCREMENT,
  `company_id` BIGINT NOT NULL,
  `contact_dept_type_id` BIGINT NOT NULL,
  `contact_mode_list` VARCHAR(1000) NOT NULL,
  `designation` VARCHAR(100) NULL DEFAULT NULL,
  `salutation` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `phone_ext` VARCHAR(10) NULL DEFAULT NULL,
  `alternate_phone` VARCHAR(20) NULL DEFAULT NULL,
  `fax` VARCHAR(45) NULL DEFAULT NULL,
  `is_primary` TINYINT NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`contact_id`),
  CONSTRAINT `fk_contact_contact_dept_type`
    FOREIGN KEY (`contact_dept_type_id`)
    REFERENCES `org`.`contact_dept_type` (`contact_dept_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `org`.`company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_contact_contact_dept_type` ON `org`.`contact` (`contact_dept_type_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_contact_company` ON `org`.`contact` (`company_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `org`.`user_activity_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `org`.`user_activity_log` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `org`.`user_activity_log` (
  `user_activity_log_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `activity_type` VARCHAR(45) NOT NULL,
  `activity_doc_pk_id` BIGINT NOT NULL,
  `activity_doc_num` VARCHAR(100) NULL DEFAULT NULL,
  `activity_detail` TEXT NULL DEFAULT NULL,
  `activity_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_activity_log_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `i_activity_dtm` ON `org`.`user_activity_log` (`activity_dtm` ASC);

SHOW WARNINGS;
CREATE INDEX `i_user_activity_dtm` ON `org`.`user_activity_log` (`user_id` ASC, `activity_dtm` ASC);

SHOW WARNINGS;
CREATE INDEX `i_activity_type` ON `org`.`user_activity_log` (`activity_type` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `org`.`company_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `org`;
INSERT INTO `org`.`company_type` (`company_type_id`, `company_type_name`, `company_type_desc`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (1, 'GROUP', 'GROUP', 1, 1, '2024-03-15 12:39:08', 1, '2024-03-15 12:39:08');
INSERT INTO `org`.`company_type` (`company_type_id`, `company_type_name`, `company_type_desc`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (2, 'COMPANY', 'COMPANY', 1, 1, '2024-03-15 12:39:08', 1, '2024-03-15 12:39:08');
INSERT INTO `org`.`company_type` (`company_type_id`, `company_type_name`, `company_type_desc`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (3, 'BUSINESS_UNIT', 'BUSINESS UNIT', 1, 1, '2024-03-15 12:39:08', 1, '2024-03-15 12:39:08');
INSERT INTO `org`.`company_type` (`company_type_id`, `company_type_name`, `company_type_desc`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (4, 'CUSTOMER', 'CUSTOMER', 1, 1, '2024-03-15 12:39:08', 1, '2024-03-15 12:39:08');

COMMIT;


-- -----------------------------------------------------
-- Data for table `org`.`company`
-- -----------------------------------------------------
START TRANSACTION;
USE `org`;
INSERT INTO `org`.`company` (`company_id`, `company_type_id`, `company_code`, `company_name`, `company_desc`, `company_logo_url`, `website`, `country`, `region`, `account_no`, `iban_no`, `swift_code`, `senior_manager_id`, `team_manager_id`, `team_lead_id`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (1, 2, 'SUN', 'SUNSHINE SOLUTIONS PVT. LTD.', 'Sunshine Solutions', NULL, NULL, '', '', NULL, NULL, NULL, NULL, 1, 1, 1, 1, '2024-05-30 10:51:54', 1, '2024-05-30 10:51:54');

COMMIT;


-- -----------------------------------------------------
-- Data for table `org`.`address_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `org`;
INSERT INTO `org`.`address_type` (`address_type_id`, `address_type_code`, `address_type_name`, `address_type_desc`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (1, 'BA', 'BILLING', 'BILLING ADDRESS', 1, 1, '2024-03-15 12:39:08', 1, '2024-03-15 12:39:08');
INSERT INTO `org`.`address_type` (`address_type_id`, `address_type_code`, `address_type_name`, `address_type_desc`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (2, 'SA', 'SHIPPING', 'SHIPPING ADDRESS', 1, 1, '2024-03-15 12:39:08', 1, '2024-03-15 12:39:08');

COMMIT;


-- -----------------------------------------------------
-- Data for table `org`.`location_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `org`;
INSERT INTO `org`.`location_type` (`location_type_id`, `location_type_code`, `location_type_name`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (1, 'HO', 'HEAD OFFICE', 1, 1, '2024-03-15 12:39:08', 1, '2024-03-15 12:39:08');
INSERT INTO `org`.`location_type` (`location_type_id`, `location_type_code`, `location_type_name`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (2, 'BO', 'BRANCH OFFICE', 1, 1, '2024-03-15 12:39:08', 1, '2024-03-15 12:39:08');

COMMIT;


-- -----------------------------------------------------
-- Data for table `org`.`contact_dept_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `org`;
INSERT INTO `org`.`contact_dept_type` (`contact_dept_type_id`, `contact_dept_type_name`, `contact_dept_type_desc`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (1, 'MANAGEMENT', 'MANAGEMENT', 1, 1, '2024-03-15 12:39:08', 1, '2024-03-15 12:39:08');
INSERT INTO `org`.`contact_dept_type` (`contact_dept_type_id`, `contact_dept_type_name`, `contact_dept_type_desc`, `status`, `created_id`, `created_dtm`, `modified_id`, `modified_dtm`) VALUES (2, 'BILLING', 'BILLING', 1, 1, '2024-03-15 12:39:08', 1, '2024-03-15 12:39:08');

COMMIT;

