-- MySQL Script generated by MySQL Workbench
-- Wed Jul 16 10:42:18 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stage
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stage` ;

-- -----------------------------------------------------
-- Schema stage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stage` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
USE `stage` ;

-- -----------------------------------------------------
-- Table `stage`.`upload_mapping_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stage`.`upload_mapping_template` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `stage`.`upload_mapping_template` (
  `upload_mapping_template_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(100) NOT NULL,
  `module_name` VARCHAR(100) NOT NULL,
  `upload_mapping_table_name` VARCHAR(100) NOT NULL,
  `upload_mapping_temp_name` VARCHAR(100) NOT NULL,
  `query` VARCHAR(1000) NOT NULL,
  `field_list` VARCHAR(1000) NOT NULL,
  `field_count` INT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`upload_mapping_template_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `stage`.`lead_stage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stage`.`lead_stage` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `stage`.`lead_stage` (
  `lead_stage_id` BIGINT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `senior_manager_id` VARCHAR(100) NULL,
  `team_manager_id` VARCHAR(100) NULL,
  `team_lead_id` VARCHAR(100) NULL,
  `assigned_to` VARCHAR(100) NULL,
  `account_number` VARCHAR(100) NULL,
  `product_type` VARCHAR(100) NULL,
  `product_account_number` VARCHAR(100) NULL,
  `agreement_id` VARCHAR(100) NULL,
  `business_name` VARCHAR(1000) NULL,
  `customer_name` VARCHAR(1000) NULL,
  `allocation_status` VARCHAR(100) NULL,
  `customer_id` VARCHAR(100) NULL,
  `passport_number` VARCHAR(100) NULL,
  `date_of_birth` VARCHAR(100) NULL,
  `bucket_status` VARCHAR(100) NULL,
  `vintage` VARCHAR(100) NULL,
  `date_of_woff` VARCHAR(100) NULL,
  `nationality` VARCHAR(100) NULL,
  `emirates_id_number` VARCHAR(100) NULL,
  `credit_limit` VARCHAR(100) NULL,
  `total_outstanding_amount` VARCHAR(100) NULL,
  `principal_outstanding_amount` VARCHAR(100) NULL,
  `employer_details` VARCHAR(200) NULL,
  `designation` VARCHAR(200) NULL,
  `company_contact` VARCHAR(100) NULL,
  `home_country_number` VARCHAR(100) NULL,
  `mobile_number` VARCHAR(100) NULL,
  `email_id` VARCHAR(100) NULL,
  `minimum_payment` VARCHAR(100) NULL,
  `ghrc_offer_1` VARCHAR(100) NULL,
  `ghrc_offer_2` VARCHAR(100) NULL,
  `ghrc_offer_3` VARCHAR(100) NULL,
  `withdraw_date` VARCHAR(100) NULL,
  `home_country_address` VARCHAR(500) NULL,
  `city` VARCHAR(100) NULL,
  `pincode` VARCHAR(100) NULL,
  `state` VARCHAR(100) NULL,
  `father_name` VARCHAR(100) NULL,
  `mother_name` VARCHAR(100) NULL,
  `spouse_name` VARCHAR(100) NULL,
  `last_paid_amount` VARCHAR(100) NULL,
  `last_paid_date` VARCHAR(100) NULL,
  `pli_status` VARCHAR(100) NULL,
  `execution_status` VARCHAR(100) NULL,
  `overdue` VARCHAR(100) NULL,
  `banker_name` VARCHAR(200) NULL,
  `is_uploaded_flag` CHAR(1) NOT NULL DEFAULT 'N',
  `reason` VARCHAR(100) NULL,
  `do_not_follow_flag` CHAR(1) NULL,
  `feedback` TEXT NULL,
  `final_feedback` TEXT NULL,
  `contactable_non_contactable` VARCHAR(100) NULL,
  `disposition_status` VARCHAR(100) NULL,
  `disposition_status_name` VARCHAR(100) NULL,
  `disposition_code` VARCHAR(100) NULL,
  `traced_source` VARCHAR(500) NULL,
  `traced_details` VARCHAR(500) NULL,
  `visa_status` VARCHAR(100) NULL,
  `mol_status` VARCHAR(100) NULL,
  `contact_info` VARCHAR(500) NULL,
  `mol_passport_no` VARCHAR(100) NULL,
  `mol_expiry_date` VARCHAR(100) NULL,
  `mol_work_permit_no` VARCHAR(45) NULL,
  `salary_in_mol` VARCHAR(45) NULL,
  `company_name_in_mol` VARCHAR(100) NULL,
  `sql_details` TEXT NULL,
  `company_trade_license_details` TEXT NULL,
  `additional_details` TEXT NULL,
  `visa_passport_no` VARCHAR(45) NULL,
  `visa_expiry_date` VARCHAR(45) NULL,
  `visa_file_number` VARCHAR(45) NULL,
  `visa_emirates` VARCHAR(45) NULL,
  `company_name_in_visa` VARCHAR(100) NULL,
  `designation_in_visa` VARCHAR(45) NULL,
  `contact_number_in_visa` VARCHAR(45) NULL,
  `unified_number` VARCHAR(45) NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `visa_emirates_id` VARCHAR(45) NULL,
  `lead_stagecol` VARCHAR(45) NULL,
  PRIMARY KEY (`lead_stage_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `stage`.`file_upload`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stage`.`file_upload` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `stage`.`file_upload` (
  `file_upload_id` BIGINT NOT NULL AUTO_INCREMENT,
  `file_type` VARCHAR(20) NOT NULL COMMENT '\'csv\',\'pdf\' etc',
  `file_name` VARCHAR(1000) NULL,
  `file_url` VARCHAR(1000) NULL,
  `company_id` BIGINT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` BIGINT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` BIGINT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`file_upload_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `i_created_id` ON `stage`.`file_upload` (`created_id` ASC);

SHOW WARNINGS;
CREATE INDEX `i_created_id_company_id` ON `stage`.`file_upload` (`created_id` ASC, `company_id` ASC, `created_dtm` ASC);

SHOW WARNINGS;
CREATE INDEX `i_file_name` ON `stage`.`file_upload` (`file_name` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
