const Joi = require("joi");

const accountsUploadSchema = Joi.object({
  senior_manager_id: Joi.string().required(),
  team_manager_id: Joi.string().required(),
  team_lead_id: Joi.string().required(),
  assigned_to: Joi.string().required(),
  account_no: Joi.string().required(),
  product_type: Joi.string().required(),
  product_account_no: Joi.string().required(),
  agreement_id: Joi.string().required(),
  business_name: Joi.string().required(),
  customer_name: Joi.string().required(),
  allocation_status: Joi.string().required(),
  cust_id: Joi.string().required(),
  passport_no: Joi.string().required(),
  dob: Joi.date().required(),
  bkt_status: Joi.string().required(),
  vintage: Joi.string().required(),
  date_of_woff: Joi.date().required(),
  nationality: Joi.string().required(),
  emirates_id_number: Joi.string().required(),
  credit_limit: Joi.string().required(),
  tos_amount: Joi.string().required(),
  pos_amount: Joi.string().required(),
  employer_details: Joi.string().required(),
  designation: Joi.string().required(),
  company_contact: Joi.string().required(),
  home_country_number: Joi.string().required(),
  mobile_number: Joi.string().required(),
  email_id: Joi.string().email().required(),
  minimum_payment: Joi.string().required(),
  ghrc_offer_1: Joi.string().required(),
  ghrc_offer_2: Joi.string().required(),
  ghrc_offer_3: Joi.string().required(),
  withdraw_date: Joi.date().required(),
  home_country_address: Joi.string().required(),
  city: Joi.string().required(),
  pincode: Joi.string().required(),
  state: Joi.string().required(),
  father_name: Joi.string().required(),
  mother_name: Joi.string().required(),
  spouse_name: Joi.string().required(),
  last_payment_amount: Joi.string().required(),
  last_payment_date: Joi.date().required(),
  pli_status: Joi.string().required(),
  execution_status: Joi.string().required(),
  banker_name: Joi.string().required(),
});

module.exports = accountsUploadSchema;
